<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <OptrisStaticGraphicsAvaloniaNativeRoot Condition="'$(OptrisStaticGraphicsAvaloniaNativeRoot)' == ''">$(MSBuildThisFileDirectory)../static/</OptrisStaticGraphicsAvaloniaNativeRoot>
    </PropertyGroup>
</Project>
